### ISSUE TITLE
Allow LunarClient

### ISSUE THREAD

**Issue by OutM4rc** [UneasyVanilla/UneasyNetwork#7]
Me and I think many others have a trash pc (MacBook Air Intel i5) and LunarClient was an excellent alternative for playing with modded Minecraft. FPS were boosted af and playing with its mod (like waypoints and 10k brightness) was really great.
I tried to install Fabric in my pc without success.
My proposal is to at least unban one the many clients. I don't think I am the only one having this problem and I think that this is stopping new players to join the server too.

**Comment by MsEDok** [comment]
Lunarclient cause issue + it come with "pre" installed mod and change that some of it is not allowed.

If you need performance check out the allowed mod list [here](https://github.com/UneasyVanilla/UneasyNetwork/blob/main/Docs/rules.md#mods)

**Comment by OutM4rc** [comment]
Which mods aren't allowed? I only know free look as a non-allowed mod, but I don't think it brings any issues.

**Comment by MsEDok** [comment]
We don't know what prebuild client add, remove, most of legit false ban come from lunar client due to most likely one of their own, added mod.
and again we have 0 idea what mod they will be adding or removing depend.

lunarclient and featherclient are basically a modpacks and we have 0 idea what mod it included.
best is to use either fabric, quilt, forge and add mod that you needed. might get better performance than "pvp client"
